Initial project generation
bitrise-io/getting-started-flutter-sample-app pull request #1
Opened 2022-11-15 15:16 UTC by hisaac

2022-11-16 09:15 UTC, ofalvai requested changes

2022-11-16 09:15 UTC, ofalvai commented on bitrise.yml
> +    stack: osx-xcode-13.2.x
Same concern as in the other repo

2022-11-21 16:33 UTC, hisaac commented on bitrise.yml
> +    stack: osx-xcode-13.2.x
This has been removed now 👍

2022-11-21 16:47 UTC, ofalvai approved these changes

2022-11-21 16:55 UTC, merged